/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    noticias: Noticia;
    paginas: Pagina;
    revistas: Revista;
    tesis: Tesis;
    facultades: Facultade;
    carreras: Carrera;
    'marco-legal': MarcoLegal;
    auditoria: Auditoria;
    autoridades: Autoridade;
    ley5189: Ley5189;
    ley5282: Ley5282;
    convenios: Convenio;
    'tribunal-miembros': TribunalMiembro;
    'tribunal-documentos': TribunalDocumento;
    'aranceles-rectorado': ArancelesRectorado;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    revistas: RevistasSelect<false> | RevistasSelect<true>;
    tesis: TesisSelect<false> | TesisSelect<true>;
    facultades: FacultadesSelect<false> | FacultadesSelect<true>;
    carreras: CarrerasSelect<false> | CarrerasSelect<true>;
    'marco-legal': MarcoLegalSelect<false> | MarcoLegalSelect<true>;
    auditoria: AuditoriaSelect<false> | AuditoriaSelect<true>;
    autoridades: AutoridadesSelect<false> | AutoridadesSelect<true>;
    ley5189: Ley5189Select<false> | Ley5189Select<true>;
    ley5282: Ley5282Select<false> | Ley5282Select<true>;
    convenios: ConveniosSelect<false> | ConveniosSelect<true>;
    'tribunal-miembros': TribunalMiembrosSelect<false> | TribunalMiembrosSelect<true>;
    'tribunal-documentos': TribunalDocumentosSelect<false> | TribunalDocumentosSelect<true>;
    'aranceles-rectorado': ArancelesRectoradoSelect<false> | ArancelesRectoradoSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navegacion: Navegacion;
    transparencia: Transparencia;
    'enlaces-externos': EnlacesExterno;
    estadisticas: Estadistica;
  };
  globalsSelect: {
    navegacion: NavegacionSelect<false> | NavegacionSelect<true>;
    transparencia: TransparenciaSelect<false> | TransparenciaSelect<true>;
    'enlaces-externos': EnlacesExternosSelect<false> | EnlacesExternosSelect<true>;
    estadisticas: EstadisticasSelect<false> | EstadisticasSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Usuarios autorizados para administrar el Portal Institucional UNC.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Define las funciones y permisos institucionales del usuario dentro del CMS.
   */
  role:
    | 'superadmin'
    | 'web-admin'
    | 'publisher'
    | 'reviewer'
    | 'editor'
    | 'correspondent'
    | 'media-manager'
    | 'auditor'
    | 'viewer';
  /**
   * Número de teléfono para notificaciones via Whatsapp y Telegram
   */
  telefono?: string | null;
  /**
   * ID del usuario en Telegram para recibir notificaciones
   */
  telegramUserId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Placeholder de blur generado automáticamente para Next.js Image.
   */
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  /**
   * Estado del flujo de aprobación editorial
   */
  approvalStatus?: ('draft' | 'en_revision' | 'rechazado' | 'aprobado' | 'publicado') | null;
  /**
   * Mostrar en la sección destacada del portal
   */
  featured?: boolean | null;
  publishedAt?: string | null;
  category: 'institucional' | 'academica' | 'investigacion' | 'extension' | 'eventos' | 'comunicados';
  /**
   * Facultad responsable de la noticia (opcional)
   */
  faculty?: (number | null) | Facultade;
  author?: string | null;
  title: string;
  /**
   * Generado automáticamente desde el título. Podés editarlo manualmente.
   */
  slug: string;
  /**
   * Aparece debajo del título en el listado y como subtítulo en el detalle. Máximo 300 caracteres.
   */
  summary: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Palabras clave para búsqueda y filtrado.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Imagen principal de la noticia. Aparece en el hero del artículo y como primera foto del carrusel al pie de página. Recomendado: 1280×720 px o superior.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Alternativa cuando la imagen no está en Media (ej: migradas de WordPress). Si existe "Imagen destacada" de Media, ese campo tiene prioridad.
   */
  featuredImageUrl?: string | null;
  /**
   * Fotos adicionales de la noticia. Junto con la imagen destacada, forman el carrusel interactivo que aparece al final del artículo. Podés agregar hasta 30 fotos.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Registro automático de cambios de estado de aprobación.
   */
  approvalHistory?:
    | {
        revisor: string;
        accion: 'sent_to_review' | 'reviewed' | 'approved' | 'rejected';
        comentario?: string | null;
        fecha: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facultades".
 */
export interface Facultade {
  id: number;
  nombre: string;
  /**
   * Generado automáticamente desde el nombre.
   */
  slug: string;
  descripcion?: string | null;
  decano?: string | null;
  email?: string | null;
  telefono?: string | null;
  imagen?: (number | null) | Media;
  activa?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: number;
  title: string;
  /**
   * Ruta completa sin barra inicial ni final (ej: "institucional/historia"). Solo minúsculas, números y guiones.
   */
  slug: string;
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            backgroundImage?: (number | null) | Media;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading: string;
            text?: string | null;
            buttonLabel: string;
            buttonUrl: string;
            style?: ('primary' | 'secondary' | 'outline') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  label: string;
                  value: string;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statistics';
          }
        | {
            ratio?: ('50-50' | '60-40' | '40-60') | null;
            left?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            right?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumn';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  photo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
      )[]
    | null;
  /**
   * Estado del flujo de aprobación editorial
   */
  approvalStatus?: ('draft' | 'en_revision' | 'rechazado' | 'aprobado' | 'publicado') | null;
  /**
   * Registro automático de cambios de estado de aprobación.
   */
  approvalHistory?:
    | {
        revisor: string;
        accion: 'sent_to_review' | 'reviewed' | 'approved' | 'rejected';
        comentario?: string | null;
        fecha: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revistas".
 */
export interface Revista {
  id: number;
  nombre: string;
  /**
   * Generado automáticamente desde el nombre. Puedes editarlo manualmente.
   */
  slug: string;
  descripcion: string;
  anioInicio: number;
  urlOjs: string;
  portada?: (number | null) | Media;
  activa?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tesis".
 */
export interface Tesis {
  id: number;
  titulo: string;
  autor: string;
  anio: number;
  resumen?: string | null;
  facultad: number | Facultade;
  urlPdf: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carreras".
 */
export interface Carrera {
  id: number;
  nombre: string;
  /**
   * Generado automáticamente desde el nombre.
   */
  slug: string;
  facultad: number | Facultade;
  duracion: number;
  titulo: string;
  modalidad?: ('Presencial' | 'Semipresencial' | 'Virtual') | null;
  descripcion?: string | null;
  resolucion?: string | null;
  tipo?: ('grado' | 'posgrado') | null;
  /**
   * Ej: Central/Concepción
   */
  sede?: string | null;
  activa?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Documentos normativos que rigen la vida institucional de la UNC.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marco-legal".
 */
export interface MarcoLegal {
  id: number;
  title: string;
  /**
   * Agrupa el documento en la página pública
   */
  category:
    | 'ley-creacion'
    | 'estatuto'
    | 'reglamento-general'
    | 'reglamentos-especiales'
    | 'codigos'
    | 'politicas'
    | 'planes'
    | 'manuales'
    | 'procedimientos'
    | 'protocolos';
  /**
   * Breve descripción del contenido del documento
   */
  description?: string | null;
  /**
   * Sube el archivo directamente. Tiene prioridad sobre la URL externa.
   */
  file?: (number | null) | Media;
  /**
   * Se usa como enlace de descarga cuando no hay archivo subido.
   */
  externalUrl?: string | null;
  /**
   * Menor número = aparece primero dentro de su categoría
   */
  order?: number | null;
  /**
   * Solo los documentos publicados se muestran en el portal
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro de eventos y acciones en el sistema
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditoria".
 */
export interface Auditoria {
  id: number;
  /**
   * Email del usuario que realizó la acción
   */
  usuario: string;
  /**
   * Rol del usuario al momento de la acción
   */
  rol?: string | null;
  accion:
    | 'login'
    | 'logout'
    | 'crear'
    | 'actualizar'
    | 'eliminar'
    | 'publicar'
    | 'cambiar_rol'
    | 'revisar'
    | 'aprobar'
    | 'rechazar'
    | 'importar'
    | 'revalidar';
  /**
   * Colección afectada (noticias, usuarios, media, etc)
   */
  coleccion?: string | null;
  /**
   * ID o título del documento afectado
   */
  documento?: string | null;
  /**
   * Fecha y hora del evento
   */
  fechaHora: string;
  /**
   * Dirección IP del cliente
   */
  ip?: string | null;
  resultado: 'exito' | 'error' | 'advertencia';
  /**
   * Descripción o mensaje del evento
   */
  mensaje?: string | null;
  /**
   * JSON con los cambios realizados (antes/después)
   */
  cambiosRelevantes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Autoridades y funcionarios de la institución con fotografías y currículum.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autoridades".
 */
export interface Autoridade {
  id: number;
  name: string;
  /**
   * Ej: Rector, Decana de la Facultad de Humanidades
   */
  role: string;
  type: 'rector' | 'vicerrector' | 'decano' | 'secretario' | 'director';
  /**
   * Facultad que dirige este/a Decano/a
   */
  faculty?: (number | null) | Facultade;
  photo?: (number | null) | Media;
  /**
   * Suba el CV en formato PDF o Word (.doc, .docx)
   */
  cvFile?: (number | null) | Media;
  /**
   * Enlace externo al CV si no se sube un archivo
   */
  cvUrl?: string | null;
  bio?: string | null;
  email?: string | null;
  /**
   * Número menor = aparece primero
   */
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Documentos requeridos por la Ley 5189/2014 sobre provisión de información en el uso de recursos públicos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ley5189".
 */
export interface Ley5189 {
  id: number;
  /**
   * Categoría exigida por la Ley 5189/2014
   */
  category:
    | 'organigrama'
    | 'direccion-telefono'
    | 'nomina-personal'
    | 'presupuesto-ingresos-gastos'
    | 'anexo-personal'
    | 'ejecucion-presupuestaria'
    | 'registro-viaticos'
    | 'bienes-patrimoniales'
    | 'funcionarios-comisionados'
    | 'otras-informaciones'
    | 'cumplimiento-art7';
  /**
   * Ej: "Enero 2024", "2024", "I Trimestre 2024"
   */
  period: string;
  /**
   * Nota breve sobre este documento específico
   */
  description?: string | null;
  /**
   * URL de Google Drive para descarga del documento
   */
  driveUrl: string;
  /**
   * Menor número = aparece primero dentro de su categoría
   */
  order?: number | null;
  /**
   * Solo los documentos publicados se muestran en el portal
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Documentos requeridos por el Art. 8° de la Ley 5282/2014 de Libre Acceso Ciudadano a la Información Pública y Transparencia Gubernamental.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ley5282".
 */
export interface Ley5282 {
  id: number;
  /**
   * Ítem exigido por el Art. 8° de la Ley 5282/2014
   */
  category:
    | 'item-1'
    | 'item-2'
    | 'item-3'
    | 'item-4'
    | 'item-5'
    | 'item-6'
    | 'item-7'
    | 'item-8'
    | 'item-9'
    | 'item-10'
    | 'item-11'
    | 'item-12'
    | 'item-13'
    | 'item-14'
    | 'item-15'
    | 'item-16'
    | 'item-17';
  /**
   * Ej: "Enero 2024", "2024", "I Trimestre 2024"
   */
  period: string;
  /**
   * Nota breve sobre este documento específico
   */
  description?: string | null;
  /**
   * URL de Google Drive para descarga del documento
   */
  driveUrl: string;
  /**
   * Menor número = aparece primero dentro de su categoría
   */
  order?: number | null;
  /**
   * Solo los documentos publicados se muestran en el portal
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "convenios".
 */
export interface Convenio {
  id: number;
  title: string;
  type: 'nacional' | 'internacional';
  year: number;
  parties: string;
  objective: string;
  signedMonth?: string | null;
  duration?: string | null;
  /**
   * URL de Google Drive del documento PDF. Dejar vacío si no hay documento disponible.
   */
  driveUrl?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tribunal-miembros".
 */
export interface TribunalMiembro {
  id: number;
  nombre: string;
  cargo: string;
  foto?: (number | null) | Media;
  /**
   * Número menor aparece primero
   */
  orden?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tribunal-documentos".
 */
export interface TribunalDocumento {
  id: number;
  titulo: string;
  tipo:
    | 'principal-cronograma'
    | 'principal-reglamento'
    | 'lista-inscriptos'
    | 'formato-notas'
    | 'padron-electoral'
    | 'candidaturas'
    | 'oficializacion'
    | 'proclamacion';
  descripcion?: string | null;
  /**
   * URL de Google Drive, MinIO, o cualquier enlace público al documento.
   */
  driveUrl?: string | null;
  orden?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Aranceles, multas y servicios cobrados directamente por el Rectorado.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aranceles-rectorado".
 */
export interface ArancelesRectorado {
  id: number;
  concepto: string;
  /**
   * Importe en guaraníes. Ej: 50000 para Gs. 50.000
   */
  monto: number;
  grupo: 'multas' | 'venta' | 'educativos';
  /**
   * Menor número aparece primero dentro del grupo.
   */
  orden?: number | null;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Preguntas frecuentes que aparecen en la página /preguntas-frecuentes del portal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * Podés incluir negritas, listas, links y más.
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'horarios' | 'admision' | 'tramites' | 'servicios' | 'transparencia' | 'rrhh' | 'titulos';
  /**
   * Número menor = aparece primero dentro de la categoría.
   */
  order?: number | null;
  active?: boolean | null;
  /**
   * Palabras clave para mejorar la búsqueda interna.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'paginas';
        value: number | Pagina;
      } | null)
    | ({
        relationTo: 'revistas';
        value: number | Revista;
      } | null)
    | ({
        relationTo: 'tesis';
        value: number | Tesis;
      } | null)
    | ({
        relationTo: 'facultades';
        value: number | Facultade;
      } | null)
    | ({
        relationTo: 'carreras';
        value: number | Carrera;
      } | null)
    | ({
        relationTo: 'marco-legal';
        value: number | MarcoLegal;
      } | null)
    | ({
        relationTo: 'auditoria';
        value: number | Auditoria;
      } | null)
    | ({
        relationTo: 'autoridades';
        value: number | Autoridade;
      } | null)
    | ({
        relationTo: 'ley5189';
        value: number | Ley5189;
      } | null)
    | ({
        relationTo: 'ley5282';
        value: number | Ley5282;
      } | null)
    | ({
        relationTo: 'convenios';
        value: number | Convenio;
      } | null)
    | ({
        relationTo: 'tribunal-miembros';
        value: number | TribunalMiembro;
      } | null)
    | ({
        relationTo: 'tribunal-documentos';
        value: number | TribunalDocumento;
      } | null)
    | ({
        relationTo: 'aranceles-rectorado';
        value: number | ArancelesRectorado;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  telefono?: T;
  telegramUserId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  approvalStatus?: T;
  featured?: T;
  publishedAt?: T;
  category?: T;
  faculty?: T;
  author?: T;
  title?: T;
  slug?: T;
  summary?: T;
  content?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featuredImage?: T;
  featuredImageUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  approvalHistory?:
    | T
    | {
        revisor?: T;
        accion?: T;
        comentario?: T;
        fecha?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              text?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        statistics?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    value?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        twoColumn?:
          | T
          | {
              ratio?: T;
              left?: T;
              right?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    photo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  approvalStatus?: T;
  approvalHistory?:
    | T
    | {
        revisor?: T;
        accion?: T;
        comentario?: T;
        fecha?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revistas_select".
 */
export interface RevistasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  anioInicio?: T;
  urlOjs?: T;
  portada?: T;
  activa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tesis_select".
 */
export interface TesisSelect<T extends boolean = true> {
  titulo?: T;
  autor?: T;
  anio?: T;
  resumen?: T;
  facultad?: T;
  urlPdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facultades_select".
 */
export interface FacultadesSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  decano?: T;
  email?: T;
  telefono?: T;
  imagen?: T;
  activa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carreras_select".
 */
export interface CarrerasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  facultad?: T;
  duracion?: T;
  titulo?: T;
  modalidad?: T;
  descripcion?: T;
  resolucion?: T;
  tipo?: T;
  sede?: T;
  activa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marco-legal_select".
 */
export interface MarcoLegalSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  description?: T;
  file?: T;
  externalUrl?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditoria_select".
 */
export interface AuditoriaSelect<T extends boolean = true> {
  usuario?: T;
  rol?: T;
  accion?: T;
  coleccion?: T;
  documento?: T;
  fechaHora?: T;
  ip?: T;
  resultado?: T;
  mensaje?: T;
  cambiosRelevantes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autoridades_select".
 */
export interface AutoridadesSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  type?: T;
  faculty?: T;
  photo?: T;
  cvFile?: T;
  cvUrl?: T;
  bio?: T;
  email?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ley5189_select".
 */
export interface Ley5189Select<T extends boolean = true> {
  category?: T;
  period?: T;
  description?: T;
  driveUrl?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ley5282_select".
 */
export interface Ley5282Select<T extends boolean = true> {
  category?: T;
  period?: T;
  description?: T;
  driveUrl?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "convenios_select".
 */
export interface ConveniosSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  year?: T;
  parties?: T;
  objective?: T;
  signedMonth?: T;
  duration?: T;
  driveUrl?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tribunal-miembros_select".
 */
export interface TribunalMiembrosSelect<T extends boolean = true> {
  nombre?: T;
  cargo?: T;
  foto?: T;
  orden?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tribunal-documentos_select".
 */
export interface TribunalDocumentosSelect<T extends boolean = true> {
  titulo?: T;
  tipo?: T;
  descripcion?: T;
  driveUrl?: T;
  orden?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aranceles-rectorado_select".
 */
export interface ArancelesRectoradoSelect<T extends boolean = true> {
  concepto?: T;
  monto?: T;
  grupo?: T;
  orden?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  active?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Estructura de navegación principal del portal (hasta 2 niveles)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navegacion".
 */
export interface Navegacion {
  id: number;
  links?:
    | {
        label: string;
        type: 'manual' | 'relationship';
        /**
         * Requerido cuando el tipo es "Manual"
         */
        url?: string | null;
        /**
         * Requerido cuando el tipo es "Relación"
         */
        page?: (number | null) | Pagina;
        newTab?: boolean | null;
        children?:
          | {
              label: string;
              type: 'manual' | 'relationship';
              /**
               * Requerido cuando el tipo es "Manual"
               */
              url?: string | null;
              /**
               * Requerido cuando el tipo es "Relación"
               */
              page?: (number | null) | Pagina;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Documentos de transparencia institucional (Ley 5189 y Ley 5282)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transparencia".
 */
export interface Transparencia {
  id: number;
  ley5189?:
    | {
        label: string;
        url?: string | null;
        nota?: string | null;
        id?: string | null;
      }[]
    | null;
  ley5282?:
    | {
        label: string;
        url?: string | null;
        nota?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Enlaces externos institucionales y contenido de información pública
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enlaces-externos".
 */
export interface EnlacesExterno {
  id: number;
  formularioTitulos?: string | null;
  urlPortalInfoPublica?: string | null;
  contenidoInfoPublica?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Estadísticas institucionales de la Universidad Nacional de Concepción
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estadisticas".
 */
export interface Estadistica {
  id: number;
  totalEstudiantes: number;
  totalDocentes: number;
  totalEgresados: number;
  totalCarrerasAcreditadas: number;
  totalFacultades: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navegacion_select".
 */
export interface NavegacionSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        page?: T;
        newTab?: T;
        children?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transparencia_select".
 */
export interface TransparenciaSelect<T extends boolean = true> {
  ley5189?:
    | T
    | {
        label?: T;
        url?: T;
        nota?: T;
        id?: T;
      };
  ley5282?:
    | T
    | {
        label?: T;
        url?: T;
        nota?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enlaces-externos_select".
 */
export interface EnlacesExternosSelect<T extends boolean = true> {
  formularioTitulos?: T;
  urlPortalInfoPublica?: T;
  contenidoInfoPublica?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estadisticas_select".
 */
export interface EstadisticasSelect<T extends boolean = true> {
  totalEstudiantes?: T;
  totalDocentes?: T;
  totalEgresados?: T;
  totalCarrerasAcreditadas?: T;
  totalFacultades?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}